# Generated by Django 3.0 on 2023-02-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cpassword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
