# Generated by Django 3.0 on 2023-02-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230223_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_price', models.CharField(blank=True, max_length=255, null=True)),
                ('product_MRP', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='products_image/')),
                ('product_stock', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
