# Generated by Django 3.0 on 2023-02-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230223_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='alt_number',
            new_name='price',
        ),
    ]
