# Generated by Django 3.0 on 2023-02-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230223_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Pending'), ('1', 'Accept'), ('2', 'Reject')], default='0', max_length=255, null=True),
        ),
    ]
